version: "3.1"
services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - persistent:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: poupachef
      MYSQL_USER: poupachef
      MYSQL_PASSWORD: poupachef
    networks:
      - app-network
volumes:
  persistent:

networks:
  app-network:
    driver: bridge
